spring:
  profiles:
    active: dev

hibernate:
  physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

jpa:
  database-platform: org.hibernate.dialect.H2Dialect