spring:
  profiles:
    active: dev
  flyway:
    enabled: true
    validate-on-migrate: true
  security:
    user:
      name: user
      password: user
  jpa:
    defer-datasource-initialization: true
hibernate:
  physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
jpa:
  database-platform: org.hibernate.dialect.H2Dialect
security:
  jwt:
    expiration: 3600000
    secret: ExtremelySecureAndLengthyPasswordThatReallyProtects123