spring:
  profiles:
    active: prod
  flyway:
    enabled: false
    validate-on-migrate: false
  jpa:
    defer-datasource-initialization: true
hibernate:
  physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
jpa:
  database-platform: org.hibernate.dialect.H2Dialect
server:
  error:
    whitelabel:
      enabled: false
    include-message: always
    include-binding-errors: always
    include-exception: false
    include-stacktrace: never