spring:
  datasource:
    url: ${DB}
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  security:
    user:
      name: user
      password: user
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: false
  flyway:
    enabled: true
    locations: classpath:db/migration/prod
    baseline-version: 0
    baseline-on-migrate: true
cors:
  allowed-origins: "*"
security:
  jwt:
    expiration: 3600000
    secret: ${JWT_SECRET}