create table address (id bigint identity not null, active bit not null, address varchar(255), cep varchar(9), city varchar(100), complement varchar(255), created_at date, number varchar(6), state varchar(100), type varchar(255) not null, uf varchar(2), customer_id bigint, primary key (id));
create table author (id bigint identity not null, name varchar(255), primary key (id));
create table book (id bigint identity not null, active bit not null, available_quantity int not null check (available_quantity>=1), created_at date not null, description varchar(1000), depth double precision, height double precision, width double precision, format varchar(255) not null, isbn varchar(255), language varchar(255) not null, pages int not null check (pages>=1), currency varchar(255) not null, price numeric(19,2) not null check (price>=1), publishing_date date not null, sku varchar(10), title varchar(255), publisher_id bigint not null, primary key (id));
create table book_author (book_id bigint not null, author_id bigint not null, primary key (book_id, author_id));
create table book_category (book_id bigint not null, category_id bigint not null, primary key (book_id, category_id));
create table book_images_url (book_id bigint not null, images_url varchar(255));
create table cart_item (id bigint identity not null, added_at datetime2 not null, currency varchar(255) not null, modified_at datetime2 not null, price numeric(19,2) not null, sub_total numeric(19,2) not null, units int not null check (units>=1), book_id bigint, customer_id bigint, primary key (id));
create table category (id bigint identity not null, active bit not null, description varchar(255), name varchar(100), primary key (id));
create table customer (user_id bigint not null, birth_date date not null, cpf varchar(255), full_name varchar(255), registered_at date, primary key (user_id));
create table delivery (id bigint identity not null, code varchar(20), created_at datetime2, finished_at datetime2, status varchar(255), address_id bigint, order_id bigint, primary key (id));
create table order_item (id bigint identity not null, price numeric(19,2) not null, sub_total numeric(19,2) not null, units int not null, book_id bigint not null, order_id bigint not null, primary key (id));
create table orders (id bigint identity not null, code varchar(20), created_at datetime2 not null, finished_at datetime2, status varchar(255) not null, total numeric(19,2) not null, customer_id bigint not null, primary key (id));
create table payment (id bigint identity not null, amount_paid numeric(19,2), created_at datetime2, modified_at datetime2, status varchar(255), order_id bigint, payment_method_id CHAR(36), primary key (id));
create table payment_method (id CHAR(36) not null, cvv varchar(3), exp_month varchar(2), exp_year varchar(4), holder varchar(255), number varchar(16), type varchar(50) not null, customer_id bigint not null, primary key (id));
create table publisher (id bigint identity not null, active bit not null, name varchar(255), site varchar(255), primary key (id));
create table roles (id bigint identity not null, role varchar(255), primary key (id));
create table users (id bigint identity not null, email varchar(50), password varchar(255), primary key (id));
create table users_roles (user_id bigint not null, roles_id bigint not null);
alter table customer add constraint UK_cwtgtb16nebxu54elskdjei66 unique (cpf);
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table address add constraint FK93c3js0e22ll1xlu21nvrhqgg foreign key (customer_id) references customer;
alter table book add constraint FKgtvt7p649s4x80y6f4842pnfq foreign key (publisher_id) references publisher;
alter table book_author add constraint FKbjqhp85wjv8vpr0beygh6jsgo foreign key (author_id) references author;
alter table book_author add constraint FKhwgu59n9o80xv75plf9ggj7xn foreign key (book_id) references book;
alter table book_category add constraint FKam8llderp40mvbbwceqpu6l2s foreign key (category_id) references category;
alter table book_category add constraint FKnyegcbpvce2mnmg26h0i856fd foreign key (book_id) references book;
alter table book_images_url add constraint FKaeeum6b1iprhmpqnun5s4n3rc foreign key (book_id) references book;
alter table cart_item add constraint FKis5hg85qbs5d91etr4mvd4tx6 foreign key (book_id) references book;
alter table cart_item add constraint FKfy7fubprxqguyp4km04eogy66 foreign key (customer_id) references customer;
alter table customer add constraint FKra1cb3fu95r1a0m7aksow0nk4 foreign key (user_id) references users;
alter table delivery add constraint FKlayueon76a86wr2gbsyannaf7 foreign key (address_id) references address;
alter table delivery add constraint FKu4e8rjwmg09vmas3ccjwglso foreign key (order_id) references orders;
alter table order_item add constraint FKb033an1f8qmpbnfl0a6jb5njs foreign key (book_id) references book;
alter table order_item add constraint FKt4dc2r9nbvbujrljv3e23iibt foreign key (order_id) references orders;
alter table orders add constraint FK624gtjin3po807j3vix093tlf foreign key (customer_id) references customer;
alter table payment add constraint FKlouu98csyullos9k25tbpk4va foreign key (order_id) references orders;
alter table payment add constraint FKjii2n6db6cje3km5ybsbgo8cl foreign key (payment_method_id) references payment_method;
alter table payment_method add constraint FK43slmstjfk0uhikc9krcvhn41 foreign key (customer_id) references customer;
alter table users_roles add constraint FKa62j07k5mhgifpp955h37ponj foreign key (roles_id) references roles;
alter table users_roles add constraint FK2o0jvgh89lemvvo17cbqvdxaa foreign key (user_id) references users;
